### ISSUE TITLE
 Not All Entities Loaded

### ISSUE THREAD

**Issue by Villagio88** [machgo/fellerwiserhomeassistant#4]
Plugin: fellerwiserhomeassistant for Home Assistant by machgo

Description:
I successfully installed the fellerwiserhomeassistant plugin for Home Assistant and was able to generate and input the security token via the Feller API. The plugin has loaded 25 entities, all of which I can control without any issues. However, it appears that not all entities are being loaded.

Steps to Reproduce:

	1.	Install the fellerwiserhomeassistant plugin for Home Assistant.
	2.	Generate the security token through the Feller API and configure it in the plugin.
	3.	Observe the entities loaded by the plugin.

Expected Behavior:
All entities should be loaded and available for control.

Actual Behavior:
Only 25 entities are loaded, while others are missing.	

Logs:
Please find the relevant logs attached
[home-assistant_2024-06-24T17-30-18.824Z.log](https://github.com/user-attachments/files/15959407/home-assistant_2024-06-24T17-30-18.824Z.log)
.

Question:
Do you have any idea what could be causing this issue? Are there any specific configurations or steps I might be missing?

Thank you for your help!

**Comment by kess78** [comment]
Message: Setup of light platform fellerwiser is taking over 10 seconds.
It's normal... the Feller WiFi Gateway is known not to be so performant

Setup of cover platform fellerwiser is taking over 10 seconds.
It's normal... the Feller WiFi Gateway is known not to be so performant

The error you get in there it's not fellerwiser related, or at least it doesn't seem to be.

On which Hardware are you running HA ?
Do you have enough RAM ?
Do you have enough horsepower ?

Try to connect to the Feller WiFi Gateway API directly using your browser and check what are the results. Are all the loads there ?

**Comment by Villagio88** [comment]
Hi Kess,

Thank you so much for your help and insights. Initially, I was running Home Assistant on a Raspberry Pi, but after reading your response, I had some concerns that the performance issues might be related to the limited hardware capabilities of the Pi. To rule this out, I’ve now set up Home Assistant in a VirtualBox on a Windows machine, allocating more than enough RAM and CPU power. Unfortunately, this hasn’t resolved the issue, so I believe the hardware is not the limiting factor here.

For your reference, I’ve attached a screenshot showing that still only 25 entities are being loaded: [Screenshot](https://share.cleanshot.com/gC41FbyZ).

Additionally, I wanted to ask about the plugin configuration. I’ve set it up by entering the IP address of my Feller WiFi Bridge (192.168.10.106) without “http://” and the security token I obtained via the Feller API account claim. You can see the configuration in this screenshot: [Configuration Screenshot](https://share.cleanshot.com/mLjbrCff).

Could you please confirm if this setup is correct? To give you a bit more context, here is how I generated the security token: [Token Generation Screenshot](https://share.cleanshot.com/FHCLw7Mt).

I am very grateful for your assistance and any further suggestions you might have!

Best regards,
Andrin Villa

**Comment by kess78** [comment]
Well, the token should be ok and the configuration also... In any case a wrong configuration leads to a non working setup and not to a partially working one.
Just to be sure, how many loads do you have here ? http://192.168.10.106/api/loads
These are the objects seen by HA integration (you need to be authenticated)

**Comment by Villagio88** [comment]
Hi Kess,

Thank you for the very quick response. I checked the URL http://192.168.10.106/api/loads and found 32 loads, as shown in this screenshot: [Screenshot](https://share.cleanshot.com/lxdPstrW).

However, according to the Wiser µGateway, there should be 35 loads, as you can see in this printscreen: [Printscreen](https://share.cleanshot.com/6S4bghqK).

I can’t quite figure out where the discrepancy comes from. If we can’t resolve this, I might reach out directly to Wiser for further assistance.

Thanks again for your continued help. I really appreciate it!

Best regards,
Andrin Villa

**Comment by kess78** [comment]
Let me guess... all your loads are there, but dali dimmers are not shown...

**Comment by Villagio88** [comment]
Hi,

Thanks again for your quick reply. You guessed it right—all my loads are there, but the DALI dimmers are not shown. Is there a solution for this issue?

I appreciate your continued support!

Best regards

**Comment by kess78** [comment]
It's because the uGateway changed the type from dim to dali, but unfortunately I don't have any in my installation.
Let me try something tonight when I'll be back home, I'll let you know.

**Comment by Villagio88** [comment]
Hi,

I can’t thank you enough for your help! I really appreciate it, and I look forward to hearing from you.

Best regards,

**Comment by kess78** [comment]
PR has been published, please try it on your setup and see what happens.
You see 35 devices on your uGateway portal and 32 devices under loads. It's normal, it's not an error.
The loads are the effective loads, the devices count on the uGateway counts also the secondary devices, not interesting for what we should do. So as far as I can see you have 3 secondary devices in you whole house. Right ?

**Comment by Villagio88** [comment]
Thank you for the quick and helpful support! After applying your PR, all the DALI dimmers are now showing up correctly, and I can control all 35 devices as expected. Everything is working perfectly now! I really appreciate your continued assistance and your prompt response to the issue.
